#include "DIO.h"

const strDIOConfigType_t astrDIOConfigParameters[DIO_GROUPS_NO] =
{
	{ PB5, INPUT, NO_CONNECTION },
	{ PB6, OUTPUT, NO_CONNECTION },
	{ PB7, INPUT, NO_CONNECTION },
	{ PB4, INPUT, NO_CONNECTION },
	{ PC0, OUTPUT, NO_CONNECTION},
	{ PC1, OUTPUT, NO_CONNECTION},
	{ PC2, OUTPUT, NO_CONNECTION},
	{ PC3, OUTPUT, NO_CONNECTION},
	{ PC4, OUTPUT, NO_CONNECTION},
	{ PC5, OUTPUT, NO_CONNECTION},
	{ PC6, OUTPUT, NO_CONNECTION},
	{ PC7, OUTPUT, NO_CONNECTION}
};